executable = /home/yuenchen/anaconda3/envs/isr/bin/python

arguments = /home/yuenchen/Domainbed/check_import.py
error = /home/yuenchen/Domainbed/dann.err
output = /home/yuenchen/Domainbed/dann.out
log = /home/yuenchen/Domainbed/dann.log
request_memory = 16G
request_disk = 20G
request_cpus = 1
request_gpus = 2
requirements = TARGET.CUDAGlobalMemoryMb  > 16000

# Set the environment
getenv = True
environment = "PYTHONPATH=/home/yuenchen/DomainBed:$PYTHONPATH"

queue

