executable = /home/yuenchen/DomainBed/run_dann.sh
error = /home/yuenchen/DomainBed/dann.err
output = /home/yuenchen/DomainBed/dann.out
log = /home/yuenchen/DomainBed/dann.log
request_memory = 16G
request_disk = 20G
request_cpus = 1
request_gpus = 2
requirements = TARGET.CUDAGlobalMemoryMb  > 16000

# Set the environment
getenv = True
environment = "PYTHONPATH=/home/yuenchen/DomainBed:$PYTHONPATH"

queue

